version: '3'
services:
    nginx:
        container_name: ${CONTAINER_SITE}-nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - /${CONTAINER_SITES_DIR}/${CONTAINER_SITE}/public:/usr/share/nginx/html
            - /${CONTAINER_SITES_DIR}/${CONTAINER_SITE}/logs/nginx:/var/log/nginx
        depends_on:
            - phpfpm
            - mariadb

    phpfpm:
        container_name: ${CONTAINER_SITE}-php
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - /${CONTAINER_SITES_DIR}/${CONTAINER_SITE}/public:/usr/share/nginx/html
    
    mariadb:
        container_name: ${CONTAINER_SITE}-mariadb
        image: mariadb:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '${MARIADB_PORT}:3306'
        environment:
            MYSQL_USER: '${WP_USER}'
            MYSQL_PASSWORD: '${WP_PASSWORD}'
            MYSQL_DATABASE: '${WP_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${WP_ROOT_PASSWORD}'
        volumes:
            - /${CONTAINER_SITES_DIR}/${CONTAINER_SITE}/mariadb:/var/lib/mysql
            - /${CONTAINER_SITES_DIR}/${CONTAINER_SITE}/docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
